### ISSUE TITLE
Turkish Language Problem

### ISSUE THREAD

**Issue by EULUSOY** [hbb20/CountryCodePickerProject#117] opened 2017-10-30 01:11 UTC
Application crashes when language is set to Turkish. It works fine in Debug mode. But it does not work in Release mode. It works in Russian, English, German without problems. Only problem in Turkish.

I updated to version 2.0.7.

**Comment by hbb20** [comment] 2017-10-30 01:44
Hey @EULUSOY, thank you for reporting. This is something unexpected as an assumed solution was implemented in v2.0.7.

@Agraphie also faced the [same issue ](https://github.com/hbb20/CountryCodePickerProject/issues/110)and created a [Pull Request](https://github.com/hbb20/CountryCodePickerProject/pull/113) with the fix. That PL was merged to v2.0.7.

@EULUSOY , we will need more details regarding the problem. Is your debug device and release testing devices are the same? What are devices? What are locale and Android versions for them? One more thing, I just want to confirm that you are not using [different versions of the library for release and debug](https://stackoverflow.com/questions/22439593/different-dependencies-for-debug-and-release-in-gradle-and-android-studio), right?

 @Agraphie can you please follow this issue and help in figuring out the solution because I can not reproduce this Turkish language issue in mine devices. Even when issue #110 was created, it was working well for me with v2.0.5.

**Comment by Agraphie** [comment] 2017-10-30 08:03
@EULUSOY please provide a stacktrace so we can help you better

**Comment by hbb20** [comment] 2017-11-01 01:24
hello @EULUSOY, is your problem solved?

**Comment by EULUSOY** [comment] 2017-11-01 03:16
Hi, @hbb20 , problem is not solved.

I tested it on the Huawei p7 phone and the Genymotion emulator (Galaxy S6 and S5).

I don't use different versions of the library for release and debug.

Everything works fine in debug mode. There is a problem only in Turkish language in release mode. I tested English, Japanese, Russian languages. There is no problem here. 

There is an XmlPullParserException exception in loadDataFromXML  method:

E/Hata: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ����h����������$������...@1:105 in java.io.InputStreamReader@5280e444) 
E/Hata: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ����h����������$������...@1:105 in java.io.InputStreamReader@52859284) 
E/Hata: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ����h����������$������...@1:105 in java.io.InputStreamReader@52823870) 
E/Hata: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ����h����������$������...@1:105 in java.io.InputStreamReader@52859ed4) 
E/Hata: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ����h����������$������...@1:105 in java.io.InputStreamReader@52854f28)

**Comment by hbb20** [comment] 2017-11-01 05:16
I checked some blog and questions. In version 2.0.8 one of the possible fixes is made. Kindly update the library version then clean and rebuild project.  

Please report the outcome so that we can keep working on the problem if required.

**Comment by EULUSOY** [comment] 2017-11-02 00:18
I tested in version 2.08. The problem is still there.

**Comment by Agraphie** [comment] 2017-11-02 08:07
I am unable to reproduce this issue. Can you try to reproduce this issue with the sample app @EULUSOY or can you give us an app/repository where we can reproduce this issue?

**Comment by EULUSOY** [comment] 2017-11-03 02:19
My problem is resolved. It's not about the library. Thank you for your understanding.

**Comment by hbb20** [comment] 2017-11-03 03:52
Great 👍

**Closed by hbb20** 2017-11-03 03:52 UTC
