### ISSUE TITLE
IndexOutOfBoundsException in CountryCodeAdapter

### ISSUE THREAD

**Issue by GrishmaPromact** [hbb20/CountryCodePickerProject#228] opened 2018-08-13 11:21 UTC
Hi @hbb20 , I am using bugfender for crashing. when app crashes in production env then we collect crash log using bugfender.
App is crashing in country code picker. 
Here is the crash report: 

**_java.lang.IndexOutOfBoundsException: Invalid index 1, size is 0
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
    at java.util.ArrayList.get(ArrayList.java:308)
    at com.hbb20.CountryCodeAdapter$4.onClick(CountryCodeAdapter.java:195)
    at android.view.View.performClick(View.java:4780)
    at android.view.ViewDebug$3.run(ViewDebug.java:826)
    at android.os.Handler.handleCallback(Handler.java:756)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5278)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)_**

I have used below code for country code picker.

                              <com.hbb20.CountryCodePicker
                                    android:id="@+id/country_code_et"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    app:ccp_autoDetectCountry="true"
                                   app:ccp_showNameCode="false" />

                            <android.support.design.widget.TextInputLayout
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:textColorHint="@color/divider"
                                app:backgroundTint="@color/divider">

                                <EditText
                                    android:id="@+id/pho_no_et"
                                    android:layout_width="match_parent"
                                    android:layout_height="wrap_content"
                                    android:hint="@string/prompt_phone"
                                    android:inputType="phone"
                                    android:digits="0123456789"
                                    android:maxLines="1"
                                    android:textSize="16sp" />
                            </android.support.design.widget.TextInputLayout>

Can you please help to resolve this issue?
Thanks.

**Comment by Jakester0813** [comment] 2018-08-20 20:48
I am also getting something like this as well. But the invalid index is 2

**Comment by ansifer** [comment] 2018-08-23 14:10
i am also getting this error with index value 6 -_-

**Comment by hbb20** [comment] 2018-08-25 01:40
@ansifer, @Jakester0813 , @GrishmaPromact  Sorry to hear that. Can you please tell me what library version are you using?

**Comment by adarshvijayanp** [comment] 2018-08-29 10:59
I'm using latest library 

**error occur when `app:ccp_autoFormatNumber="true"`  is turn on.**

> when i selected country code - India - +91  , when i entering the 6th number in edit text this error occur and app crashed
> 
>  java.lang.IndexOutOfBoundsException: setSpan (7 ... 7) ends beyond length 6

        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
        at android.text.Selection.setSelection(Selection.java:76)
        at android.text.Selection.setSelection(Selection.java:87)
        at com.hbb20.InternationalPhoneTextWatcher.afterTextChanged(InternationalPhoneTextWatcher.java:153)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:8014)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10175)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1043)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:560)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:491)
        at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
        at android.widget.TextView.doKeyDown(TextView.java:6103)
        at android.widget.TextView.onKeyDown(TextView.java:5916)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2654)
        at android.view.View.dispatchKeyEvent(View.java:9243)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:379)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2395)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1727)
        at android.app.Activity.dispatchKeyEvent(Activity.java:2735)
        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4139)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4101)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3799)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3856)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5969)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5908)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5869)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3446)
    	at andro

**IndexOutOfBoundsException:** is different for different country code. example for USA - when i type the 4th number

   java.lang.IndexOutOfBoundsException: setSpan (5 ... 5) ends beyond length 4

**Comment by hbb20** [comment] 2018-08-29 12:45
Thank you so much for detailed issue. Can post the edit text configuration
and key strokes to reproduce this?

**Comment by GrishmaPromact** [comment] 2018-08-29 12:56
@hbb20 Before i used `com.hbb20:ccp:2.1.2` when crash occurred.
Now, i have changed version to `com.hbb20:ccp:2.2.2`.
After that crash not occurred. I don't know why the crash occurred?

**Comment by hbb20** [comment] 2018-08-29 14:33
In prior version, there was one known problem where it was crashing in
specific case. Which should be fixed by latest version.

**If someone find this issue with v2.2.2 or higher, please post back
editText configuration, selected country, and key strokes to enter number.
That will help us investigate the issue.**

**Comment by hbb20** [comment] 2018-08-29 14:36
@adarshvijayanp, can you try by using inputtype = "phone"?

**Comment by adarshvijayanp** [comment] 2018-08-30 11:16
@hbb20  i changed inputType - number to phone, now it work fine without any crash.

my  **edit text configuration**     inputType = number
 ```
<com.hbb20.CountryCodePicker
                    android:id="@+id/cpp_contact_number"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:ccp_countryPreference="in,ae,us"
                    />


                <EditText
                    android:id="@+id/et_alternate_contact_number"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:inputType="number"
                    />
```
 selected country code - India - +91 , 
 editText value:  908040    ( then my app crashed, it doesn't matter which number you entered, app crashing after entering 6th number)



---- another small issue i found that when i select country as USA (as you shown in sample 

 [](https://github.com/hbb20/CountryCodePickerProject/wiki/Full-Number-Support#2-auto-formatting) 

auto formatting format entered number as  **469-664-1777** instead of  **(469) 664-1777**  --missing brackets. 
I don't know why?.

**Comment by hbb20** [comment] 2018-08-30 12:41
Can you please use type as phone for now? Thanks.

Regarding US number, the bracket format is national format. Earlier CCP was
trying to follow that. Later we decided to go for international format
(which is without bracket for USA) because CCP is being used in various
countries.

**Comment by adarshvijayanp** [comment] 2018-08-31 05:48
OK, Thank You For Your Contribution.

**Closed** 2018-10-01 17:52 UTC
