### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Jparrgam** [hbb20/CountryCodePickerProject#311] opened 2019-05-15 23:29 UTC
Hi All,
identify this bug

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
       at com.hbb20.CCPCountry.isEligibleForQuery(CCPCountry.java:1717)
       at com.hbb20.CountryCodeAdapter.getFilteredCountries(CountryCodeAdapter.java:158)
       at com.hbb20.CountryCodeAdapter.applyQuery(CountryCodeAdapter.java:131)
       at com.hbb20.CountryCodeAdapter.onBindViewHolder(CountryCodeAdapter.java:28)
       at com.hbb20.CountryCodeAdapter$2.onTextChanged(CountryCodeAdapter.java:90)
       at android.widget.TextView.sendOnTextChanged(TextView.java:8226)
       at android.widget.TextView.handleTextChanged(TextView.java:8288)
       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10410)
       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1214)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:844)
       at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:198)
       at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:345)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:91)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by hbb20** [comment] 2019-05-16 01:23
het @Jparrgam , thank you for posting. Can you please post the version of CCP that you are using? Because, older builds had known issues which was solved in subsequent releases. Here is the same problem reporting https://github.com/hbb20/CountryCodePickerProject/issues/254. 

If it solves the problem, please let us know so that we can close the issue else please post steps to reproduce.

**Comment by RubensHardt** [comment] 2019-05-29 22:04
Hey @hbb20, I'm having the same error using the 2.2.9 version. It happens when you try to search for a country in the editText of the dialog. The issue is in the method isEligibleForQuery:

boolean isEligibleForQuery(String query) {
        query = query.toLowerCase();
        return getName().toLowerCase().contains(query) || getNameCode().toLowerCase().contains(query) || getPhoneCode().toLowerCase().contains(query) || getEnglishName().toLowerCase().contains(query);
    }

The getEnglishName() method is returning null.

**Comment by Jparrgam** [comment] 2019-06-18 01:17
hi @hbb20 the error persists

**Comment by hbb20** [comment] 2019-08-03 18:44
@RubensHardt thank you for finding getEnglishName()  giving null... This will help find problem.

**Comment by hbb20** [comment] 2019-08-04 00:15
Thank you for reporting. We just released new version `v2.3.0` with this fix. Please check and let us know if it does not work as expected.

**Closed by hbb20** 2019-08-04 00:15 UTC

**Comment by sagarrishabh** [comment] 2019-11-14 13:34
@hbb20 Hey, the version 2.3.0 is based on AndroidX. I'm not able to fix this crash, any suggestion?
