### ISSUE TITLE
CountryCodeAdapter.java -> IndexOutOfBoundsException

### ISSUE THREAD

**Issue by huergomartin** [hbb20/CountryCodePickerProject#137] opened 2017-12-04 15:10 UTC
Hi, I am having the follow crash report:

Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 3, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.hbb20.CountryCodeAdapter$4.onClick(CountryCodeAdapter.java:195)
       at android.view.View.performClick(View.java:4780)
       at android.view.ViewDebug$3.run(ViewDebug.java:826)
       at android.os.Handler.handleCallback(Handler.java:756)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5263)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by beast-shubham** [comment] 2017-12-04 18:13
+1

**Comment by huergomartin** [comment] 2017-12-04 22:02
@hbb20 the crash is occasional, Crashlytics reports only in two cases.
In xml I am using it inside a FrameLayout:

` <com.hbb20.CountryCodePicker
                    android:id="@+id/ccp"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="bottom"
                    android:layout_marginLeft="16dp"
                    android:layout_marginStart="16dp"
                    app:ccp_showNameCode="true"
                    app:ccp_textSize="@dimen/text_size_marca_nav" />`

Java file only to get the prefix number:
` CountryCodePicker ccp = (CountryCodePicker) findViewById(R.id.ccp);
`
inside a ClickListener:
`                    String number = ccp.getSelectedCountryCodeWithPlus() + editText_phone.getText().toString();
`

**Comment by hbb20** [comment] 2017-12-14 04:52
A possible fix has been applied in version 2.1.1. If the problem is still there, please comment here.
Thanks.

**Closed by hbb20** 2017-12-14 04:52 UTC
