### ISSUE TITLE
Problem in android 6.0

### ISSUE THREAD

**Issue by salunkhenilesh** [hbb20/CountryCodePickerProject#26] opened 2016-12-10 06:00 UTC
getting problem for only for android version 6.0,
error
android.view.InflateException: Binary XML file line #38: Binary XML file line #38: Error inflating class com.hbb20.CountryCodePicker

**Comment by hbb20** [comment] 2016-12-10 06:02
Which version of library you are using? Can you post your gradle file

**Comment by salunkhenilesh** [comment] 2016-12-10 06:40
compile 'com.hbb20:ccp:1.7.1'

**Comment by hbb20** [comment] 2016-12-10 06:52
Can you post other libraries used from gradle file? Because it's working
correctly on 6.0.1 for me.

**Comment by salunkhenilesh** [comment] 2016-12-10 06:58
compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.hbb20:ccp:1.7.1'
    compile 'com.android.support:cardview-v7:24.2.1'
    compile 'com.android.support:recyclerview-v7:24.2.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.android.volley:volley:1.0.0'
    compile 'com.crystal:crystalpreloaders:1.0.0'
    compile 'com.afollestad.material-dialogs:core:0.9.1.0'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'com.google.android.gms:play-services-ads:8.1.0'
    compile 'com.google.android.gms:play-services-gcm:8.4.0'
    testCompile 'junit:junit:4.12'
    compile 'com.onesignal:OneSignal:3.+@aar'


these libraries used

**Comment by hbb20** [comment] 2016-12-10 07:05
Well one possible problem is mismatch of support library version used. CCP
uses v23.2.1 for appcompat, support and card view and you are using 24.2.1.

Just for checking purpose, change your support library version to 23.2.1
from 24.2.1 (for appcompat, support and card view). If that works correctly
means the problem is related to library version mismatch.

**Comment by salunkhenilesh** [comment] 2016-12-10 07:39
The following classes could not be instantiated:
- com.hbb20.CountryCodePicker (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.NoSuchFieldError: CountryCodePicker   at com.hbb20.CountryCodePicker.applyCustomProperty(CountryCodePicker.java:114)   at com.hbb20.CountryCodePicker.init(CountryCodePicker.java:108)   at com.hbb20.CountryCodePicker.<init>(CountryCodePicker.java:89)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard

**Comment by hbb20** [comment] 2016-12-10 07:46
In such cases, mostly clean project / rebuild project solves issue. Try
them from Build->Rebuild project/ Clean project.

**Comment by hbb20** [comment] 2016-12-11 10:06
Did that solve your problem?

**Comment by hbb20** [comment] 2017-01-06 07:44
I'm closing this issue. Reopen it if you feel need.

**Closed by hbb20** 2017-01-06 07:44 UTC

**Comment by Joeeeyy** [comment] 2017-07-11 19:02
Attempt to invoke virtual method 'java.lang.String com.hbb20.CountryCodePicker.getSelectedCountryCodeWithPlus()' on a null object reference
This happens when I try to get the country code and attach it to my phone no edittext. Am I supposed to initialize it with the new operator or xml declaration and findviewbyid are sufficient?

**Comment by hbb20** [comment] 2017-07-12 02:14
@Joeeeyy Sorry for the trouble. 

findViewById() will do everything and no extra work is required.

Can you provide following details?
- CCP Library version that you are using
- Specific XML layout file
- Code Snippet of java file (or entire java file if you feel comfortable)
- Expected behaviour

I request you to open [new issue](https://github.com/hbb20/CountryCodePickerProject/issues/new) for specific problem rather than commenting on closed issue.

**Comment by ajaytiwari1** [comment] 2018-02-08 12:29
Binary XML file line #108: Error inflating class com.hbb20.CountryCodePicker can you hellp me out m stuck
compile 'com.hbb20:ccp:1.7.2'
Then compile 'com.hbb20:ccp:2.1.2' 
Both are not working 'com.android.support:appcompat-v7:25.1.1'

**Comment by ajaytiwari1** [comment] 2018-02-08 12:31
Error inflating class com.hbb20.CountryCodePicker

**Comment by hbb20** [comment] 2018-02-08 15:07
This is something you can try, set this in your gradle file
```
compile ('com.hbb20:ccp:2.1.2',{
exclude group: 'com.android.support'
})
```
This will avoid inclusion of support libraries for CCP which are of 26 level and causing the error.

And make sure to include support library for recyclerview, appcompat of level 25. So part of your gradle file dependencies should look like this.
```
   compile ('com.hbb20:ccp:2.1.2',{
        exclude group: 'com.android.support'
    })
    compile 'com.android.support:recyclerview-v7:25.1.1'
    compile 'com.android.support:appcompat-v7:25.1.1'
```

Let me know if it worked or not..

**Comment by ajaytiwari1** [comment] 2018-02-09 04:28
Error:Failed to resolve: com.android.support:appcompat-v7:26.1.0


Error:Failed to resolve: com.android.support:recyclerview-v7:26.1.0



i got this error

**Comment by hbb20** [comment] 2018-02-09 07:05
But you are using 'com.android.support:appcompat-v7:25.1.1' ( versio 25.1.1) right?
Can you show us your gradle file?

**Comment by ajaytiwari1** [comment] 2018-02-12 05:15
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')

    compile files('libs/otto-1.3.5.jar')
    compile files('libs/gcm.jar')
    compile project(':route_library')
    compile files('libs/jsoup-1.6.0.jar')
    compile project(':library')

    compile project(':EBS')
    compile('com.android.support:appcompat-v7:25.1.1') {
        exclude module: 'support-v4'
    }

    compile 'com.hbb20:ccp:1.7.2'


    compile 'com.android.support:appcompat-v7:25.1.1'
    compile 'com.android.support:cardview-v7:25.1.1'
    compile 'com.android.support:recyclerview-v7:25.1.1'
    compile 'com.google.android.gms:play-services:10.2.6'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.android.support:design:25.3.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.github.lzyzsd:circleprogress:1.1.0@aar'
    compile 'com.google.android.gms:play-services-analytics:10.2.6'
    compile 'com.google.code.gson:gson:2.3'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.google.android.gms:play-services-maps:10.2.6'
    compile 'com.google.maps.android:android-maps-utils:0.4.4'
    compile 'com.google.android.gms:play-services-gcm:10.2.6'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'org.apache.httpcomponents:httpmime:4.2.3'
    testCompile 'junit:junit:4.12'
}

repositories {
    mavenCentral()
}

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.0'
    useLibrary 'org.apache.http.legacy'
    dexOptions {
        javaMaxHeapSize "4g"
    }
    lintOptions {
        checkReleaseBuilds true
    }

    defaultConfig {
        applicationId "com.test.test1"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 48
        versionName "3.8"
        multiDexEnabled true

    }
    buildTypes {
        release {

            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        sourceSets {
            main {
                res.srcDirs = ['src/main/res', 'src/main/res/drawable-hdpi', 'src/main/res/drawable-sw720']
            }
        }
    }


}

**Comment by hbb20** [comment] 2018-02-12 06:01
Just to confirm, did you try by replacing 
this line 
`
compile 'com.hbb20:ccp:1.7.2'
`
in your gradle with
```
compile ('com.hbb20:ccp:2.1.2',{
exclude group: 'com.android.support'
})
```
then click `sync` option.

this will upgrade your library version to 2.1.2. (For new android studios, 1.7.2 will not render correct preview) 

You might need to do [some changes](https://github.com/hbb20/CountryCodePickerProject/wiki/Update-Guide-for-v2.0.0)

**Comment by ajaytiwari1** [comment] 2018-02-12 08:49
yes i did but it not works

**Comment by ajaytiwari1** [comment] 2018-02-12 08:52
Error:Failed to resolve: com.android.support:appcompat-v7:26.1.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/home/astraqube/Desktop/Runnning NEWUI/newUI/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by hbb20** [comment] 2018-02-12 14:34
Try by clicking ```Install Repository and sync project``` in Android Studio.


```
compile ('com.hbb20:ccp:2.1.2',{
exclude group: 'com.android.support'
})
``` 
will exclude all support libraries of ccp and should use the version from your own gradle (in your case it will be 25.1.1).

**Comment by Amr-Elmadah** [comment] 2018-04-14 00:54
the same problem here, 
" android.view.InflateException: Binary XML file line #61: Binary XML file line #61: Error inflating class com.hbb20.CountryCodePicker
    Caused by: android.view.InflateException: Binary XML file line #61: Error inflating class com.hbb20.CountryCodePicker"
even after adding  exclude group
compile ('com.hbb20:ccp:2.1.9',{
exclude group: 'com.android.support'
})

**Comment by Amr-Elmadah** [comment] 2018-04-15 05:39
Emulator : Pixel 2
Android version : 8.1
used : com.android.support:appcompat-v7:27.0.2
